import "../styles/globals.scss";
import "react-multi-carousel/lib/styles.css";
import Head from "next/head";

import { CommerceProvider } from "@bigcommerce/storefront-data-hooks";
import Navbar from "../components/Navbar";

function MyApp({ Component, pageProps }) {
  return (
    <CommerceProvider locale={"en-US"}>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
            integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
            crossOrigin="anonymous"
            referrerpolicy="no-referrer"
          />
        </Head>
        <Navbar />
        <Component {...pageProps} />
      </div>
    </CommerceProvider>
  );
}

export default MyApp;
